version: '3'
services:
  app:
    build:
      context: .
    ports:
      - '3000:3000'
    depends_on:
      - redis
    environment:
      - REDIS_DSN=redis://redis:6379
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'